/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef CreateVolume_CONSTANTS_H
#define CreateVolume_CONSTANTS_H

#include "CreateVolume_types.h"



class CreateVolumeConstants {
 public:
  CreateVolumeConstants();

};

extern const CreateVolumeConstants g_CreateVolume_constants;



#endif
