/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "CreateVolume_constants.h"



const CreateVolumeConstants g_CreateVolume_constants;

CreateVolumeConstants::CreateVolumeConstants() {
}



